[package]
name = "a_logger"
version = "0.1.0"
edition = "2021"
authors = ["Sivese <codeguru.sivese@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {  version = "0.24.1" }
env_logger = {  version = "0.10.1" }